Vagrant.configure("2") do |config|


  # config.vm.provider.memory = 512


  config.vm.define "server01" do |server01|
    server01.vm.box =  "ubuntu/bionic64"
    server01.vm.provi "shell", path: "provi.sh"
    server01.vm.hostname = "server01"
    server01.vm.network "forwarded_port", guest: 80, host: 8080
  end

  # config.vm.define "server02" do |server02|
  #    server02.vm.box =  "ubuntu/bionic64"
  #   server02.vm.hostname = "server02"
  #
  # end
  config.vm.define "server02" do |server02|
    server02.vm.box =  "ubuntu/bionic64"
    server02.vm.provi "shell", path: "provi.sh"
    server02.vm.hostname = "server02"
    server02.vm.network "forwarded_port", guest: 80, host: 8081
  end

end
